"""empty message

Revision ID: 65048921c583
Revises: 0e91b1c2ef71
Create Date: 2023-01-14 20:09:25.332282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65048921c583'
down_revision = '0e91b1c2ef71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('eyes_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('eyes_color')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
