"""empty message

Revision ID: 9c0941921a99
Revises: cccc3fd218d2
Create Date: 2023-04-04 15:04:10.517796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0941921a99'
down_revision = 'cccc3fd218d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users_fav_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_fav_planets',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    op.drop_table('user')
    op.drop_table('user_planet')
    op.drop_table('user_characters')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.String(length=50), nullable=True))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravity', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=20), nullable=True))
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('surface_water')
        batch_op.drop_column('gravity')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('homeworld')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('mass')

    op.create_table('user_characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('characters_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], name='user_characters_characters_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_characters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_characters_pkey')
    )
    op.create_table('user_planet',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='user_planet_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_planet_user_id_fkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('users_fav_planets')
    op.drop_table('users_fav_characters')
    op.drop_table('users')
    # ### end Alembic commands ###
